# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc import federated_pb2 as federated__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in federated_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FederatedLearningStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConnectClient = channel.unary_unary(
                '/aegishealth.FederatedLearning/ConnectClient',
                request_serializer=federated__pb2.ConnectRequest.SerializeToString,
                response_deserializer=federated__pb2.ConnectResponse.FromString,
                _registered_method=True)
        self.GetGlobalModel = channel.unary_unary(
                '/aegishealth.FederatedLearning/GetGlobalModel',
                request_serializer=federated__pb2.ModelRequest.SerializeToString,
                response_deserializer=federated__pb2.ModelResponse.FromString,
                _registered_method=True)
        self.SubmitUpdate = channel.unary_unary(
                '/aegishealth.FederatedLearning/SubmitUpdate',
                request_serializer=federated__pb2.UpdateRequest.SerializeToString,
                response_deserializer=federated__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/aegishealth.FederatedLearning/Heartbeat',
                request_serializer=federated__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=federated__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.DisconnectClient = channel.unary_unary(
                '/aegishealth.FederatedLearning/DisconnectClient',
                request_serializer=federated__pb2.DisconnectRequest.SerializeToString,
                response_deserializer=federated__pb2.DisconnectResponse.FromString,
                _registered_method=True)
        self.TrainingStream = channel.stream_stream(
                '/aegishealth.FederatedLearning/TrainingStream',
                request_serializer=federated__pb2.ClientMessage.SerializeToString,
                response_deserializer=federated__pb2.ServerMessage.FromString,
                _registered_method=True)


class FederatedLearningServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ConnectClient(self, request, context):
        """Edge agent connects to orchestrator
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGlobalModel(self, request, context):
        """Edge agent requests current global model
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitUpdate(self, request, context):
        """Edge agent submits local model update
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Edge agent sends heartbeat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisconnectClient(self, request, context):
        """Edge agent disconnects when shutting down
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainingStream(self, request_iterator, context):
        """Bidirectional stream for real-time coordination
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FederatedLearningServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConnectClient': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectClient,
                    request_deserializer=federated__pb2.ConnectRequest.FromString,
                    response_serializer=federated__pb2.ConnectResponse.SerializeToString,
            ),
            'GetGlobalModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGlobalModel,
                    request_deserializer=federated__pb2.ModelRequest.FromString,
                    response_serializer=federated__pb2.ModelResponse.SerializeToString,
            ),
            'SubmitUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitUpdate,
                    request_deserializer=federated__pb2.UpdateRequest.FromString,
                    response_serializer=federated__pb2.UpdateResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=federated__pb2.HeartbeatRequest.FromString,
                    response_serializer=federated__pb2.HeartbeatResponse.SerializeToString,
            ),
            'DisconnectClient': grpc.unary_unary_rpc_method_handler(
                    servicer.DisconnectClient,
                    request_deserializer=federated__pb2.DisconnectRequest.FromString,
                    response_serializer=federated__pb2.DisconnectResponse.SerializeToString,
            ),
            'TrainingStream': grpc.stream_stream_rpc_method_handler(
                    servicer.TrainingStream,
                    request_deserializer=federated__pb2.ClientMessage.FromString,
                    response_serializer=federated__pb2.ServerMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aegishealth.FederatedLearning', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aegishealth.FederatedLearning', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FederatedLearning(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConnectClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegishealth.FederatedLearning/ConnectClient',
            federated__pb2.ConnectRequest.SerializeToString,
            federated__pb2.ConnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGlobalModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegishealth.FederatedLearning/GetGlobalModel',
            federated__pb2.ModelRequest.SerializeToString,
            federated__pb2.ModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegishealth.FederatedLearning/SubmitUpdate',
            federated__pb2.UpdateRequest.SerializeToString,
            federated__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegishealth.FederatedLearning/Heartbeat',
            federated__pb2.HeartbeatRequest.SerializeToString,
            federated__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisconnectClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegishealth.FederatedLearning/DisconnectClient',
            federated__pb2.DisconnectRequest.SerializeToString,
            federated__pb2.DisconnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrainingStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/aegishealth.FederatedLearning/TrainingStream',
            federated__pb2.ClientMessage.SerializeToString,
            federated__pb2.ServerMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
